-- create GROOM table
CREATE TABLE `GROOM` (
  `GROOM_ID` int NOT NULL AUTO_INCREMENT,
  `GROOM_NAME` varchar(100) NOT NULL,
  `BRIDE_ID` int DEFAULT NULL,
  PRIMARY KEY (`GROOM_ID`),
  UNIQUE KEY `GROOM_UN` (`BRIDE_ID`),
  CONSTRAINT `GROOM_FK` FOREIGN KEY (`BRIDE_ID`) REFERENCES `BRIDE` (`BRIDE_ID`)
)

-- create BRIDE table
CREATE TABLE `BRIDE` (
  `BRIDE_ID` int NOT NULL AUTO_INCREMENT,
  `BRIDE_NAME` varchar(100) NOT NULL,
  `GROOM_ID` int DEFAULT NULL,
  PRIMARY KEY (`BRIDE_ID`),
  UNIQUE KEY `BRIDE_UN` (`GROOM_ID`),
  CONSTRAINT `BRIDE_FK` FOREIGN KEY (`GROOM_ID`) REFERENCES `GROOM` (`GROOM_ID`)
)

-- insert GROOM table
INSERT INTO GROOM(GROOM_NAME) VALUES ('이태우')
INSERT INTO GROOM(GROOM_NAME) VALUES ('김두렬')
INSERT INTO GROOM(GROOM_NAME) VALUES ('임동욱')

-- insert BRIDE table
INSERT INTO BRIDE(BRIDE_NAME) VALUES ('김지혜')
INSERT INTO BRIDE(BRIDE_NAME) VALUES ('안예지')
INSERT INTO BRIDE(BRIDE_NAME) VALUES ('김아영')

-- update GROOM table
UPDATE GROOM SET GROOM.BRIDE_ID = 1 WHERE GROOM_ID =1
UPDATE GROOM SET GROOM.BRIDE_ID = 2 WHERE GROOM_ID =2
-- update BRIDE table
UPDATE BRIDE SET BRIDE.GROOM_ID = 1 WHERE BRIDE_ID =1
UPDATE BRIDE SET BRIDE.GROOM_ID = 2 WHERE BRIDE_ID =2

-- SELECT
SELECT * FROM GROOM g
LEFT OUTER JOIN BRIDE b
ON g.BRIDE_ID = b.BRIDE_ID
UNION
SELECT * FROM GROOM g
RIGHT OUTER JOIN BRIDE b
ON g.BRIDE_ID = b.BRIDE_ID

-- 결과
1	이태우	1	1	김지혜	1
2	김두렬	2	2	안예지	2
3	임동욱
			    3	김아영
