-- create parent table
CREATE TABLE `GRADE` (
  `GRADE_NO` tinyint NOT NULL,
  `GRADE_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`GRADE_NO`)
)

-- insert parent table
INSERT INTO GRADE VALUES(1,'1학년')
INSERT INTO GRADE VALUES(2,'2학년')
INSERT INTO GRADE VALUES(2,'2학년')

-- craete child table
CREATE TABLE `CLASS` (
  `GRADE_NO` tinyint NOT NULL,
  `CLASS_NO` tinyint NOT NULL,
  `CLASS_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`GRADE_NO`,`CLASS_NO`),
  CONSTRAINT `CLASS_FK` FOREIGN KEY (`GRADE_NO`) REFERENCES `GRADE` (`GRADE_NO`)
)

-- insert child table
INSERT INTO CLASS VALUES(1,1,'1반')
INSERT INTO CLASS VALUES(1,2,'2반')
INSERT INTO CLASS VALUES(1,3,'3반')
INSERT INTO CLASS VALUES(1,4,'4반')
INSERT INTO CLASS VALUES(1,5,'5반')
INSERT INTO CLASS VALUES(2,1,'1반')
INSERT INTO CLASS VALUES(2,2,'2반')
INSERT INTO CLASS VALUES(2,3,'3반')
INSERT INTO CLASS VALUES(2,4,'4반')
INSERT INTO CLASS VALUES(2,5,'5반')
INSERT INTO CLASS VALUES(3,1,'1반')
INSERT INTO CLASS VALUES(3,2,'2반')
INSERT INTO CLASS VALUES(3,3,'3반')
INSERT INTO CLASS VALUES(3,4,'4반')
INSERT INTO CLASS VALUES(3,5,'5반')

-- select GRADE , CLASS
SELECT g.GRADE_NO ,c.CLASS_NO , g.GRADE_NAME , c.CLASS_NAME
FROM CLASS c
INNER JOIN GRADE g
ON c.GRADE_NO = g.GRADE_NO

-- 결과
1	1	1학년	1반
1	2	1학년	2반
1	3	1학년	3반
1	4	1학년	4반
1	5	1학년	5반
2	1	2학년	1반
2	2	2학년	2반
2	3	2학년	3반
2	4	2학년	4반
2	5	2학년	5반
3	1	3학년	1반
3	2	3학년	2반
3	3	3학년	3반
3	4	3학년	4반
3	5	3학년	5반

-- 1 : M 관계를 가지는 table 생성 완료