-- create STUDENT table
CREATE TABLE `STUDENT` (
  `STUDENT_ID` int NOT NULL AUTO_INCREMENT,
  `STUDENT_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`STUDENT_ID`)
)

-- create SUBJECT table
CREATE TABLE `SUBJECT` (
  `SUBJECT_ID` int NOT NULL AUTO_INCREMENT,
  `SUBJECT_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`SUBJECT_ID`)
)

-- create 수강신청 table
CREATE TABLE `수강신청` (
  `STUDENT_ID` int NOT NULL,
  `SUBJECT_ID` int NOT NULL,
  KEY `수강신청_FK` (`STUDENT_ID`),
  KEY `수강신청_FK_1` (`SUBJECT_ID`),
  CONSTRAINT `수강신청_FK` FOREIGN KEY (`STUDENT_ID`) REFERENCES `STUDENT` (`STUDENT_ID`),
  CONSTRAINT `수강신청_FK_1` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `SUBJECT` (`SUBJECT_ID`)
)

-- insert STUDNET table
INSERT INTO STUDENT(STUDENT_NAME) VALUES ('이태우')
INSERT INTO STUDENT(STUDENT_NAME) VALUES ('김지혜')

-- insert SUBJECT table
INSERT INTO SUBJECT(SUBJECT_NAME) VALUES('국어')
INSERT INTO SUBJECT(SUBJECT_NAME) VALUES('수학')
INSERT INTO SUBJECT(SUBJECT_NAME) VALUES('JAVA')

-- insert 수강신청 table
INSERT INTO 수강신청 VALUES (1,1)
INSERT INTO 수강신청 VALUES (1,3)
INSERT INTO 수강신청 VALUES (2,1)
INSERT INTO 수강신청 VALUES (2,2)

-- SELECT
SELECT * FROM 수강신청 sg
JOIN STUDENT st
ON sg.STUDENT_ID = st.STUDENT_ID
JOIN SUBJECT sb
ON sg.SUBJECT_ID = sb.SUBJECT_ID
ORDER BY st.STUDENT_ID

-- 결과
1	1	1	이태우	1	국어
1	3	1	이태우	3	JAVA
2	1	2	김지혜	1	국어
2	2	2	김지혜	2	수학